### ISSUE TITLE
Is there a way to cancel createChatCompletionsStream ?

### ISSUE THREAD

**Issue by ConfusedVorlon** [SwiftBeta/SwiftOpenAI#16]
Firstly - thank you for a great library. It has made it really easy to get streaming chat completions.

One issue though; I can't see a way to terminate the stream once it has started. Am I missing something?

thank you.

**Comment by SwiftBeta** [comment]
Thank you for your comment! You are right; this feature hasn't been implemented yet

**Comment by SwiftBeta** [comment]
Created a new release `0.8.0`, now the `Stop` type accepts an Array of Strings (based on this issue https://github.com/SwiftBeta/SwiftOpenAI/issues/17)

The only way of cancelling a Stream using the `Stop` parameter
