### ISSUE TITLE
Support iOS 15.0+

### ISSUE THREAD

**Issue by neelvirdy** [SwiftBeta/SwiftOpenAI#19]
I'd like to migrate to use this package, but I get the following error when I attempt to import SwiftOpenAI:

`Compiling for iOS 15.0, but module 'SwiftOpenAI' has a minimum deployment target of iOS 16.0`

My app is committed to supporting iOS 15.0+ so this is currently preventing me from switching to this package.

**Comment by SwiftBeta** [comment]
New release created [0.9.0](https://github.com/SwiftBeta/SwiftOpenAI/releases/tag/0.9.0)
- Added support iOS 13+ and macOS 12+

Thanks for opening an issue 👍
