### ISSUE TITLE
How do you use other models from modelList?

### ISSUE THREAD

**Issue by srector13** [SwiftBeta/SwiftOpenAI#22]
I am trying to use the gpt-3.5-turbo-16k model for chat completions but I am not sure how to use this in the createChatCompletions method.

**Comment by SwiftBeta** [comment]
You can select the model using the enum value:

```swift
.gpt3_5(.gpt_3_5_turbo_16k)
```

For instance, in place of using [here](https://github.com/SwiftBeta/SwiftOpenAI#code-examples-using-the-api) ```.gpt3_5(.turbo)```, you can use ```.gpt3_5(.gpt_3_5_turbo_16k)```
