### ISSUE TITLE
No Working: uncaught signal: 5

### ISSUE THREAD

**Issue by tingspain** [SwiftBeta/SwiftOpenAI#23]
Hello, 

I am trying to use the library of a M1 Max, but i am getting the following error:

`Plug-in ended with uncaught signal: 5)`

Any idea how to solve it? I have been investigating a little and It seems that some of the dependences are not compatible with the apple SoC. 

Thanks in advance

**Comment by SwiftBeta** [comment]
Hello @tingspain I have developed and tested the full SDK using M1 Max, please provide more information or a demo project to check this error 👍
