### ISSUE TITLE
App example?

### ISSUE THREAD

**Issue by surak** [SwiftBeta/SwiftOpenAI#33]
Hi, 

I host one of these OpenAI-API compatible inference servers for academics ( just like https://chat.lmsys.org ), and I was thinking about making an IOS app which would talk to such a server.

Turns out I'm a zero on swift, and Xcode is overwhelming from the first sight, to say the least.

The examples in the README lead me to nowhere. I have absolutely no idea how to transform this repo into a useful app. 

A minimal example which one could clone and try would be amazingly welcome.

A second thing is that this repo is hardcoded to talk to OpenAI, but not to openai-compatible servers. This is something you might have some interest in. Check the example of https://Continue.dev - they allow you also to point to private inference servers.

Thanks!

**Comment by SwiftBeta** [comment]
Hey!

Big thanks for dropping your ideas here. Just added a Demo app to the repo for a quick start on the Swift/Xcode journey. It’s a simple example to clone and play with for creating your iOS app to connect with an OpenAI-API compatible server.

Regarding the idea to adjust the repo for chatting with openai-compatible servers, It’s a cool suggestion but currently, we're zooming in on OpenAI services. Maybe something to explore in the future, but it's not planned for the next iterations of SwiftOpenAI SDK
