### ISSUE TITLE
Demo App Help?

### ISSUE THREAD

**Issue by thatvirtualboy** [SwiftBeta/SwiftOpenAI#38]
I've added my API Key to the `SwiftOpenAI.plist` file. The app launches, but all requests are failing. E.g., when creating an image:

Error creating Images with DALL·E:  The operation couldn’t be completed. (SwiftOpenAI.OpenAIAPIError error 1.)

Am I missing any other requirements? Thanks

**Comment by SwiftBeta** [comment]
Hello, I have literally compiled the demo app (added my API Token), and it's working. Check if you have created your token correctly; it should work fine with the following code:

https://github.com/SwiftBeta/SwiftOpenAI/blob/main/Demo/Demo/CreateImages/CreateImageViewModel.swift

<img src="https://github.com/SwiftBeta/SwiftOpenAI/assets/74316958/da3d31d9-2289-461c-a11a-cd438745e4ce" width="300">

**Comment by thatvirtualboy** [comment]
Gah! My billing was messed up so it was erroring out. Thanks for the reply :)
