### ISSUE TITLE
TopP should be a double, not Int in Chat Completion

### ISSUE THREAD

**Issue by maxmai-proactiveailab** [SwiftBeta/SwiftOpenAI#39]
TopP should be a double, not Int in Chat Completion
See OpenAI doc: https://platform.openai.com/docs/api-reference/chat/create#chat-create-top_p

**Comment by SwiftBeta** [comment]
Thanks for sharing. It has been [merged](https://github.com/SwiftBeta/SwiftOpenAI/pull/40), and I created a [new release](https://github.com/SwiftBeta/SwiftOpenAI/releases/tag/1.6.1)
